# Generated by Django 4.2.2 on 2024-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoornotification',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
