# Generated by Django 4.2.2 on 2024-10-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_outdoornotification_is_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.SmallIntegerField(choices=[(0, 'Order Placed'), (1, 'Report'), (2, 'Public')], default=0),
        ),
    ]
