# Generated by Django 4.2.2 on 2023-06-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_name', models.CharField(max_length=100)),
                ('extension_sip_number', models.CharField(max_length=100)),
                ('extension_sip_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Janus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janus_name', models.CharField(max_length=100)),
                ('janus_domain', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pbx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbx_name', models.CharField(max_length=100)),
                ('pbx_domain', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_token', models.CharField(max_length=50)),
                ('short_url', models.CharField(blank=True, max_length=150, null=True)),
                ('auth_token', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[(1, 'Y'), (2, 'N')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.extension')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extension',
            name='janus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.janus'),
        ),
        migrations.AddField(
            model_name='extension',
            name='pbx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pbx'),
        ),
    ]
