# Generated by Django 4.2.2 on 2023-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1),
        ),
    ]
