# Generated by Django 4.2.2 on 2023-06-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dialer_user_extension_user_global_user_janus_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialer',
            name='user',
        ),
    ]
