# Generated by Django 4.2.2 on 2023-08-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='description',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='note',
        ),
    ]
