# Generated by Django 4.2.2 on 2023-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_description_complain_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain',
            field=models.SmallIntegerField(choices=[(0, 'Not Working'), (1, 'Have Some issue'), (2, 'Other')], default=0),
        ),
    ]
