# Generated by Django 4.2.2 on 2023-08-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_complain_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_id',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
