# Generated by Django 4.2.2 on 2023-08-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_complain_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
