# Generated by Django 4.2.2 on 2023-08-27 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_complain_complain_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
