# Generated by Django 4.2.2 on 2023-08-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_complain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Complained'), (1, 'Processing'), (2, 'Completed'), (3, 'Canceled')], default=0, null=True),
        ),
    ]
