# Generated by Django 4.2.2 on 2023-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_complain_id_complain_complain_placed_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
