# Generated by Django 4.2.2 on 2023-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_service_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
