# Generated by Django 4.2.2 on 2024-05-20 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0026_complain_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Main Terms Policies',
            },
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.termheading')),
            ],
            options={
                'verbose_name_plural': 'Section Policies',
            },
        ),
    ]