# Generated by Django 4.2.2 on 2024-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_termheading_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='termheading',
            name='page',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Terms and Conditions'), (1, 'Privacy Policy'), (2, 'Shipping Policy'), (3, 'Refund Policy')], null=True),
        ),
    ]
