# Generated by Django 4.2.2 on 2024-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_termheading_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subheading',
            old_name='head',
            new_name='main',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='content',
            new_name='sub_content',
        ),
        migrations.RenameField(
            model_name='subheading',
            old_name='title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='termheading',
            old_name='content',
            new_name='main_content',
        ),
        migrations.RenameField(
            model_name='termheading',
            old_name='heading',
            new_name='main_title',
        ),
    ]
