# Generated by Django 4.2.2 on 2024-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_rename_head_subheading_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheading',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='termheading',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
