# Generated by Django 4.2.2 on 2024-01-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_fcm_token_user_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tgram_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
