# Generated by Django 4.2.2 on 2024-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_channel_name_user_tgram_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tgram_token',
        ),
    ]
