# Generated by Django 4.2.2 on 2024-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outdoor_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
