# Generated by Django 4.2.2 on 2024-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_outdoor_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_clientid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='razorpay_clientsecret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
