# Generated by Django 4.2.2 on 2024-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_gst_number_user_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
