# Generated by Django 4.2.2 on 2024-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_tax_rate_alter_user_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
