# Generated by Django 4.2.2 on 2024-09-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bot_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
