# Generated by Django 4.2.2 on 2024-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Food'), (1, 'Non-Food')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
