# Generated by Django 4.2.2 on 2024-09-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
