# Generated by Django 4.2.2 on 2024-09-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_bot_token'),
        ('accounts', '0013_user_business_type_alter_user_bot_token'),
    ]

    operations = [
    ]
