# Generated by Django 4.2.2 on 2023-06-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartt',
        ),
    ]
