# Generated by Django 4.2.2 on 2023-07-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_cart_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
