# Generated by Django 4.2.2 on 2023-07-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
