# Generated by Django 4.2.2 on 2023-07-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_remove_item_category_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='stores.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='stores.subcategory'),
        ),
    ]
