# Generated by Django 4.2.2 on 2023-09-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_servicecart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecart',
            name='price',
        ),
    ]
