# Generated by Django 4.2.2 on 2023-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
