# Generated by Django 4.2.2 on 2023-09-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_complain_service_alter_complain_complain'),
        ('stores', '0022_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(editable=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.serviceorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='dashboard.service')),
            ],
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='services',
            field=models.ManyToManyField(related_name='stores_order_services', to='stores.serviceorderitem'),
        ),
    ]
