# Generated by Django 4.2.2 on 2024-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0029_outdoororderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoororder',
            name='items',
            field=models.ManyToManyField(related_name='stores_outdoor_order_items', to='stores.outdoororderitem'),
        ),
    ]
