# Generated by Django 4.2.2 on 2024-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0030_alter_outdoororder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoorcart',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
