# Generated by Django 4.2.2 on 2024-02-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_temporary_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_users',
            name='order_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='temporary_users',
            name='receipt',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
