# Generated by Django 4.2.2 on 2024-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_temporary_users_order_id_temporary_users_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_users',
            name='order_total',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
