# Generated by Django 4.2.2 on 2024-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_temporary_users_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporary_users',
            old_name='order_id',
            new_name='custom_order_id',
        ),
        migrations.AddField(
            model_name='temporary_users',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
