# Generated by Django 4.2.2 on 2024-05-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_rename_order_id_temporary_users_custom_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'sub categories'},
        ),
    ]
