# Generated by Django 4.2.2 on 2024-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0037_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoorcart',
            name='cart_user_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
