# Generated by Django 4.2.2 on 2024-05-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0038_outdoorcart_cart_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outdoorcart',
            unique_together=set(),
        ),
    ]
