# Generated by Django 4.2.2 on 2024-08-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_alter_outdoorcart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
