# Generated by Django 4.2.2 on 2024-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0040_item_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax_rate',
            field=models.IntegerField(choices=[(0, 'Nil%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=0),
        ),
    ]
