# Generated by Django 4.2.2 on 2024-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0041_alter_item_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoororder',
            name='overall_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
