# Generated by Django 4.2.2 on 2024-10-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0045_remove_temporary_users_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoororder',
            name='temp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.temporary_users'),
        ),
    ]
