# Generated by Django 4.2.2 on 2024-10-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0046_outdoororder_temp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outdoororder',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
